import React from 'react'

export const metadata = {
  title: "Setting app",
  description: "Generated by create next app",
};

export default function layout({children}) {
  return (
    <>
    <div>layout tool of setting</div>
    {children}
    </>
    
  )
}

